rm -r out

mkdir out

java -version

set -e
CLASSPATH=lib/accessors-smart-1.1.jar:lib/spring-aop-4.3.6.RELEASE.jar:lib/android-json-0.0.20131108.vaadin1.jar:lib/spring-aspects-4.3.6.RELEASE.jar:lib/antlr-2.7.7.jar:lib/spring-beans-4.3.6.RELEASE.jar:lib/asm-5.0.3.jar:lib/spring-boot-1.5.1.RELEASE.jar:lib/aspectjweaver-1.8.9.jar:lib/spring-boot-autoconfigure-1.5.1.RELEASE.jar:lib/assertj-core-2.6.0.jar:lib/spring-boot-starter-1.5.1.RELEASE.jar:lib/classmate-1.3.3.jar:lib/spring-boot-starter-aop-1.5.1.RELEASE.jar:lib/dom4j-1.6.1.jar:lib/spring-boot-starter-data-jpa-1.5.1.RELEASE.jar:lib/evo-inflector-1.2.1.jar:lib/spring-boot-starter-data-rest-1.5.1.RELEASE.jar:lib/h2-1.4.193.jar:lib/spring-boot-starter-jdbc-1.5.1.RELEASE.jar:lib/hamcrest-core-1.3.jar:lib/spring-boot-starter-logging-1.5.1.RELEASE.jar:lib/hamcrest-library-1.3.jar:lib/spring-boot-starter-test-1.5.1.RELEASE.jar:lib/hibernate-commons-annotations-5.0.1.Final.jar:lib/spring-boot-starter-tomcat-1.5.1.RELEASE.jar:lib/hibernate-core-5.0.11.Final.jar:lib/spring-boot-starter-web-1.5.1.RELEASE.jar:lib/hibernate-entitymanager-5.0.11.Final.jar:lib/hibernate-jpa-2.1-api-1.0.0.Final.jar:lib/hibernate-validator-5.3.4.Final.jar:lib/spring-context-4.3.6.RELEASE.jar:lib/jackson-annotations-2.8.0.jar:lib/spring-core-4.3.6.RELEASE.jar:lib/jackson-core-2.8.6.jar:lib/spring-data-commons-1.13.0.RELEASE.jar:lib/jackson-databind-2.8.6.jar:lib/spring-data-jpa-1.11.0.RELEASE.jar:lib/jandex-2.0.0.Final.jar:lib/spring-data-rest-core-2.6.0.RELEASE.jar:lib/javassist-3.21.0-GA.jar:lib/spring-data-rest-webmvc-2.6.0.RELEASE.jar:lib/javax.transaction-api-1.2.jar:lib/spring-expression-4.3.6.RELEASE.jar:lib/jboss-logging-3.3.0.Final.jar:lib/spring-hateoas-0.23.0.RELEASE.jar:lib/jcl-over-slf4j-1.7.22.jar:lib/spring-jdbc-4.3.6.RELEASE.jar:lib/json-path-2.2.0.jar:lib/spring-orm-4.3.6.RELEASE.jar:lib/json-smart-2.2.1.jar:lib/spring-plugin-core-1.2.0.RELEASE.jar:lib/jsonassert-1.4.0.jar:lib/jul-to-slf4j-1.7.22.jar:lib/spring-tx-4.3.6.RELEASE.jar:lib/spring-web-4.3.6.RELEASE.jar:lib/log4j-over-slf4j-1.7.22.jar:lib/spring-webmvc-4.3.6.RELEASE.jar:lib/logback-classic-1.1.9.jar:lib/tomcat-embed-core-8.5.11.jar:lib/logback-core-1.1.9.jar:lib/tomcat-embed-el-8.5.11.jar:lib/tomcat-embed-websocket-8.5.11.jar:lib/tomcat-jdbc-8.5.11.jar:lib/objenesis-2.1.jar:lib/tomcat-juli-8.5.11.jar:lib/slf4j-api-1.7.22.jar:lib/validation-api-1.1.0.Final.jar:lib/snakeyaml-1.17.jar:lib/spring-boot-test-1.5.1.RELEASE.jar:lib/spring-boot-test-autoconfigure-1.5.1.RELEASE.jar:lib/spring-test-4.3.6.RELEASE.jar:lib/junit-4.12.jar:lib/mockito-core-1.10.19.jar

javac -cp $CLASSPATH -d out -sourcepath src $(find src -name '*.java')

java -cp $CLASSPATH:out  com/example/RestfulPeopleApplication
